# Hands On do Word2Vec

## Setup

In [1]:
import spacy

spacy.cli.download('pt_core_news_lg')

✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_lg')


## Experimentos

### Experimento 1: spaCy

In [2]:
import spacy

nlp = spacy.load("pt_core_news_lg")

#exemplo = "conversar falar"

#exemplo = "conversar correr"

#exemplo = "homem mulher"

exemplo = "Roma Itália"

doc = nlp(exemplo)

tokens = [token for token in doc]

In [3]:
tokens

[Roma, Itália]

In [4]:
tokens[0].similarity(tokens[1])

0.6953800916671753

In [5]:
doc1 = nlp("BTG é o melhor banco")
doc2 = nlp("BTG não é o melhor banco")

doc1.similarity(doc2)

0.9587788611888292

### Experimento 2: CBOW do NILC

*1* - Baixe o modelo treinado de word embedding "CBOW 50 dimensões" do site do NILC (http://nilc.icmc.usp.br/nilc/index.php/repositorio-de-word-embeddings-do-nilc)

2 - Coloque o arquivo extraído "cbow_s50.txt" na mesma pasta no drive deste notebook

3 - Monte o drive no menu à esquerda

4 - Ache o arquivo e nas opções escolha "copiar caminho". Cole na célular de código abaixo.

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
cbow = "/content/drive/MyDrive/SI/modulo 6/PROGRAMAÇÃO/cbow_s50.txt"

In [8]:
from scipy.spatial.distance import cosine

from gensim.models import KeyedVectors

modelo_cbow = KeyedVectors.load_word2vec_format(cbow)

In [9]:
wordvec_word1 = modelo_cbow['paris']

wordvec_word1

array([-0.020294,  0.194442, -0.541309,  0.130813,  0.379075,  0.099368,
        0.141254,  0.6645  ,  0.275922,  0.041167, -0.195588,  0.033338,
       -0.108194,  0.147469,  0.050603,  0.137108,  0.126018, -0.206659,
        0.030714,  0.366886,  0.178358,  0.414669, -0.541905, -0.046735,
       -0.258853,  0.246684,  0.20393 ,  0.446218, -0.168388,  0.245471,
        0.362905, -0.102444,  0.10675 , -0.436719, -0.256444,  0.018533,
        0.149703, -0.155646, -0.114772,  0.162537,  0.056663,  0.084701,
       -0.362806,  0.195091,  0.01294 , -0.175672, -0.04856 ,  0.145635,
       -0.075486, -0.029708], dtype=float32)

In [10]:
wordvec_word2 = modelo_cbow['sushi']
wordvec_word2

array([ 0.051048, -0.263931,  0.395657,  0.0657  ,  0.241834,  0.160043,
       -0.075289, -0.000853,  0.339915,  0.00448 , -0.120207, -0.171502,
       -0.295024, -0.225415,  0.440629,  0.112848, -0.079396, -0.41122 ,
       -0.301952,  0.06505 ,  0.10868 ,  0.19933 , -0.14556 ,  0.272603,
        0.275773, -0.243797, -0.007372,  0.401474, -0.108795,  0.02331 ,
        0.163243,  0.11058 ,  0.174046, -0.054328,  0.224306, -0.15568 ,
        0.18777 , -0.141561, -0.281716,  0.38672 ,  0.074273,  0.263462,
       -0.094089,  0.040878, -0.238047,  0.15192 ,  0.050724,  0.089781,
       -0.486567,  0.299459], dtype=float32)

In [11]:
(wordvec_word1, wordvec_word2)
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cosine.html

(array([-0.020294,  0.194442, -0.541309,  0.130813,  0.379075,  0.099368,
         0.141254,  0.6645  ,  0.275922,  0.041167, -0.195588,  0.033338,
        -0.108194,  0.147469,  0.050603,  0.137108,  0.126018, -0.206659,
         0.030714,  0.366886,  0.178358,  0.414669, -0.541905, -0.046735,
        -0.258853,  0.246684,  0.20393 ,  0.446218, -0.168388,  0.245471,
         0.362905, -0.102444,  0.10675 , -0.436719, -0.256444,  0.018533,
         0.149703, -0.155646, -0.114772,  0.162537,  0.056663,  0.084701,
        -0.362806,  0.195091,  0.01294 , -0.175672, -0.04856 ,  0.145635,
        -0.075486, -0.029708], dtype=float32),
 array([ 0.051048, -0.263931,  0.395657,  0.0657  ,  0.241834,  0.160043,
        -0.075289, -0.000853,  0.339915,  0.00448 , -0.120207, -0.171502,
        -0.295024, -0.225415,  0.440629,  0.112848, -0.079396, -0.41122 ,
        -0.301952,  0.06505 ,  0.10868 ,  0.19933 , -0.14556 ,  0.272603,
         0.275773, -0.243797, -0.007372,  0.401474, -0.108795,  0

In [12]:
sum_vectors = wordvec_word1 + wordvec_word2
sum_vectors

array([ 0.030754  , -0.069489  , -0.145652  ,  0.196513  ,  0.620909  ,
        0.259411  ,  0.06596499,  0.663647  ,  0.615837  ,  0.045647  ,
       -0.315795  , -0.138164  , -0.403218  , -0.07794601,  0.491232  ,
        0.249956  ,  0.046622  , -0.61787903, -0.271238  ,  0.431936  ,
        0.287038  ,  0.613999  , -0.68746495,  0.225868  ,  0.01692   ,
        0.002887  ,  0.196558  ,  0.847692  , -0.277183  ,  0.268781  ,
        0.52614796,  0.008136  ,  0.280796  , -0.491047  , -0.032138  ,
       -0.137147  ,  0.33747298, -0.297207  , -0.39648798,  0.549257  ,
        0.130936  ,  0.348163  , -0.456895  ,  0.23596899, -0.225107  ,
       -0.02375199,  0.002164  ,  0.235416  , -0.56205297,  0.269751  ],
      dtype=float32)

In [13]:
cosine(wordvec_word1, wordvec_word2)

0.7932539880275726

## Desafio

Use algum modelo Word2Vec para processar o dataset e obter um dataframe com outras features (faça isso separado da versão que vocês já tem com BoW).

In [14]:
import pandas as pd
import numpy as np
import math 


In [15]:
# Abrindo o dataset 
df = pd.read_csv("/content/drive/MyDrive/SI/modulo 6/PROGRAMAÇÃO/ResultadoProcessamento.csv")

In [16]:
tokenized_test = df['Frases_sem_stop_words'][:21]
tokenized_test

0                           ['Minuto', 'touro', 'ouro']
1                                               ['Sim']
2     ['Queria', 'saber', 'Btg', 'banking', 'própria...
3                                                    []
4                                                    []
5     ['Vamos', 'ajudar', 'Brasil', 'principal', 'ca...
6     ['tanta', 'conta', 'digital', 'dando', 'baile'...
7     ['Instagram', 'deixa', 'publicar', 'imagens', ...
8                                              ['Cadê']
9     ['aqui', 'apenas', 'mostrar', 'apreço', 'mulhe...
10                                                   []
11    ['Eita', 'existe', 'ninguém', 'pra', 'responde...
12    ['mandei', 'pergunta', 'privado', 'vcs', 'resp...
13    ['alocar', 'valor', 'nessa', 'nova', 'atualiza...
14    ['recomendo', 'maior', 'banco', 'investimentos...
15                                       ['Disciplina']
16                                                   []
17                              ['horário', 'esp

In [21]:
def word2vec(tokenized_test):
    array_full = []
    for x in tokenized_test:
        
        modelo_cbow(x)
        print(modelo_cbow)
        # array_full.append(x)
        # return array_full
        

In [22]:
oi = ['horário', 'especial']
testk  = word2vec(oi)
testk

TypeError: ignored

In [ ]:
# Criando um data frame de teste para validar o pré processamento
data_test = {'id': [1, 2, 3, 4, 5],
             'dataPublicada': ['03/01/2022', '03/04/2022', '03/07/2022', '03/10/2022', '31/12/2022'],
             'autor': ['btgpactual', 'robert87', 'grace46', 'william25', 'john23'],
             'texto': ["Obrigado, 🚀🚀💙", "Bom dia, gostaria de saber como faço pra conseguir falar com um atendente humanizado no chat do btg banking?", 
                       "Bom dia, preciso urgente do meu informe de rendimentos do BTLG11, para declaração do meu IR. Já enviei vários e-mails e até o momento sem resposta. Telefone ninguém atende. Como faço?", "Pessoal, sempre muito bom mas se eu puder solicitar uma coisa seria legendas 😅", "Sempre é aproveitoso parar o q tá fazendo para ouvi-lo"],
             'sentimento': ['NEUTRAL', 'NEUTRAL', 'NEGATIVE', 'POSITIVE', 'POSITIVE'],
             'tipoInteracao': ["comentário", "comentário", "comentário", "marcação", "comentário"],
             'anomalia': [1, 0, 0, 1, 1],
             'probabilidadeAnomalia': [100, 20, 30, 100, 100],
             'linkPost': ['https://www.instagram.com/p/CapXhB5Lvas/#17935401550894179', 'https://www.instagram.com/p/CaqBiRpsYLm/', 'https://www.instagram.com/p/CaqBiRpsYLm/', 'https://www.instagram.com/p/CapXhB5Lvas/#17926096268158628', 'https://www.instagram.com/p/CaR1j2TuPpD/#17914683365221503'],
             'processado': [0,0,0,1,1],
             'contemHyperlink': [0,0,0,1,1],
             'tokenizacao':["a","b","c","d","e"]}

df_testing = pd.DataFrame(data_test)
df_testing

In [ ]:
oi = {'a': ['hello','world','new','input']}